### ISSUE TITLE
Support for running on a Java 17 jenkins node

### ISSUE THREAD

**Issue by vnonchev-mentormate** [jenkinsci/nexus-platform-plugin#204]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.332.2
OS: Linux - 4.14.276-211.499.amzn2.x86_64
---
nexus-jenkins-plugin:3.14.412.v8021dc9cc4ef
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Both controller and agent are using amazon linux. Both have Java 17 distrubution by AWS (Corretto)

$ java -version
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Corretto-17.0.3.6.1 (build 17.0.3+6-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.3.6.1 (build 17.0.3+6-LTS, mixed mode, sharing)

### Reproduction steps

Just running nexus evaluation in scripted pipelines like so:
                    def policyEvaluationResult = script.nexusPolicyEvaluation(failBuildOnNetworkError: false, iqApplication: 'webapp', iqStage: 'stage',
                            iqScanPatterns: nexusScanPatterns(foldersList), jobCredentialsId: '')

### Expected Results

No error

### Actual Results

The evaluation fails and the following exception is thrown:

`Remote call on EC2 (dev-aws) - node-spot (i-06cc8528e364b0894) failed
[Pipeline] echo
 java.io.IOException: Remote call on EC2 (dev-aws) - node-spot (i-06cc8528e364b0894) failed
 	at hudson.remoting.Channel.call(Channel.java:1004)
 	at hudson.remoting.VirtualChannel$call.call(Unknown Source)
 	at org.sonatype.nexus.ci.iq.IqPolicyEvaluatorUtil.evaluatePolicy(IqPolicyEvaluatorUtil.groovy:95)
 	at org.sonatype.nexus.ci.iq.IqPolicyEvaluatorUtil$evaluatePolicy.call(Unknown Source)
 	at org.sonatype.nexus.ci.iq.PolicyEvaluatorExecution.run(PolicyEvaluatorExecution.groovy:50)
 	at org.sonatype.nexus.ci.iq.PolicyEvaluatorExecution.run(PolicyEvaluatorExecution.groovy)
 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: java.lang.ExceptionInInitializerError
 	at hidden.com.thoughtworks.xstream.converters.collections.PropertiesConverter.marshal(PropertiesConverter.java:71)
 	at hidden.com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
 	at hidden.com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
 	at hidden.com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
 	at hidden.com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
 	at hidden.com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
 	at hidden.com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
 	at hidden.com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
 	at hidden.com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
 	at hidden.com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
 	at hidden.com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
 	at hidden.com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
 	at hidden.com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
 	at hidden.com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
 	at hidden.com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
 	at hidden.com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
 	at hidden.com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
 	at hidden.com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
 	at hidden.com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:83)
 	at hidden.com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
 	at hidden.com.thoughtworks.xstream.XStream.marshal(XStream.java:1266)
 	at hidden.com.thoughtworks.xstream.XStream.marshal(XStream.java:1255)
 	at hidden.com.thoughtworks.xstream.XStream.toXML(XStream.java:1228)
 	at hidden.com.thoughtworks.xstream.XStream.toXML(XStream.java:1215)
 	at hidden.com.sonatype.insight.scan.model.io.ScanWriter.openScan(ScanWriter.java:142)
 	at com.sonatype.nexus.api.iq.scan.Scanner.scan(Scanner.java:106)
 	at com.sonatype.nexus.api.iq.impl.DefaultIqClient.scan(DefaultIqClient.java:255)
 	at com.sonatype.nexus.api.iq.impl.DefaultIqClient.scan(DefaultIqClient.java:233)
 	at com.sonatype.nexus.api.iq.internal.InternalIqClient$scan.call(Unknown Source)
 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
 	at org.sonatype.nexus.ci.iq.RemoteScanner.call(RemoteScanner.groovy:106)
 	at org.sonatype.nexus.ci.iq.RemoteScanner.call(RemoteScanner.groovy)
 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
 	at hudson.remoting.Request$2.run(Request.java:376)
 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:833)
 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to EC2 (dev-aws) - node-spot (i-06cc8528e364b0894)
 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
 		at hudson.remoting.Channel.call(Channel.java:1000)
 		at hudson.remoting.VirtualChannel$call.call(Unknown Source)
 		at org.sonatype.nexus.ci.iq.IqPolicyEvaluatorUtil.evaluatePolicy(IqPolicyEvaluatorUtil.groovy:95)
 		at org.sonatype.nexus.ci.iq.IqPolicyEvaluatorUtil$evaluatePolicy.call(Unknown Source)
 		at org.sonatype.nexus.ci.iq.PolicyEvaluatorExecution.run(PolicyEvaluatorExecution.groovy:50)
 		at org.sonatype.nexus.ci.iq.PolicyEvaluatorExecution.run(PolicyEvaluatorExecution.groovy)
 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 		at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field protected volatile java.util.Properties java.util.Properties.defaults accessible: module java.base does not "opens java.util" to unnamed module @3e94b121
 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
 	at hidden.com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:40)
 	at hidden.com.thoughtworks.xstream.converters.collections.PropertiesConverter$Reflections.<clinit>(PropertiesConverter.java:105)
 	... 41 more
 
`

### Anything else?

I could see that the plugin already has support for binaries built by Java 17 which is awesome! Is there currently another workaround like passing JVM flags such as `--add-exports=java.base/java.util=ALL-UNNAMED` to make it work? 
Thank you for the great plugin!

**Comment by eduard-tita** [comment]
Hi @vnonchev-mentormate. Thank you for opening this issue.

This is technically not a bug, since our plugin works with Java 8 and 11, those being the only Java versions fully supported by Jenkins as of now - see: https://www.jenkins.io/doc/administration/requirements/java/

When Jenkins will officially support Java 17 (not the case yet), we will make sure our plugin works with it. Until then it's a low priority.

**Comment by eduard-tita** [comment]
I'm not sure I fully understand your needs. If you just want to build/test your projects with Java 17, you don't have to run the agents on Java 17. I would not run them on Java 17 yet. I don't think many plugins are ready for that.

There are at least a couple of ways to achieve this. For instance, you can run the agents on Java 11 and install Java 17 as a global tool in Jenkins. Then you use the tool in your pipeline for build/test purposes. 

E.g. assuming your project is maven based, your build stage in the pipeline could look something like:
```
stage('Build') {
    tools {
        jdk 'jdk-17'
        maven 'maven-3.8.4' 
    }
    steps {
        sh 'mvn -B -DskipTests clean package'
    }
}
```
I hope it helps. Again, I'm not entirely sure I understand your use case.

**Comment by eduard-tita** [comment]
Hi @vnonchev-mentormate. I don't know how your agents are set up, so I really cannot suggest a solution. They could run standalone, as services, as Docker containers etc. Passing `--add-exports=java.base/java.util=ALL-UNNAMED` to the agent's JVM is not different that let's say setting up the maximum heap size, which very much depend on the agents setup. This is related to the general Jenkins setup and it's beyond the scope of this plugin.

Again, I would not recommend running the agents on Java 17 yet. If your pipelines require Jenkins plugins, it is likely some of them will not work at all or not as expected. You will create a set of unnecessary problems for yourself. And even if you solve all of them for now, there's no guaranty that Jenkins agent and plugins updates will not bring up new ones.

I would highly recommend separating the underlying java instance used to run the agents from the java instance(s) needed to build/test your projects. This approach has many advantages and none of the drawbacks of running everything in a single JVM.
